stages:
  - test
  - publish

test:
  stage: test
  image: node:lts
  before_script:
    - yarn install
  script:
    - yarn lint
    - yarn test
  coverage: '/Lines\s*:\s*(\d*\.?\d+)%/'
  artifacts:
    when: always
    paths:
      - coverage
      - mochawesome-report
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - node_modules/

pages:
  stage: publish
  image: node:lts
  before_script:
    - yarn install
  script:
    - yarn run doc
    - mv doc public
  artifacts:
    paths:
      - public
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - node_modules/
  only:
    - master